'use strict';
const D=GAME_DATA,G=GAME,A=ART,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE_KEY='dark-expedition.save.v2';let run=null,chosenClass='marine',view='home',inspected=null,modal='',busy=false,fast=false,lastFocus=null,storageAvailable=true,discardMode=false;
try{fast=localStorage.getItem('dark-expedition.fast.v2')==='1';}catch{storageAvailable=false;}
let chosenDifficulty='veteran',chosenCampaign='crusade',playback=null;
const types={attack:'攻击',skill:'战术',reaction:'应对',equipment:'装备'};
function saved(){try{return G.restore(localStorage.getItem(SAVE_KEY));}catch{return null;}}
function save(){if(!run)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(run));storageAvailable=true;}catch{storageAvailable=false;toast('浏览器无法保存进度，请保持页面开启。');}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function btn(label,action,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function art(key,cls=''){return A.icon(key,cls);}
function header(){return `<header class="topbar"><button class="wordmark" data-action="home" aria-label="任务主菜单">${art('eagle')}<span>黑暗远征<small>DARK EXPEDITION</small></span></button><div class="top-center"><span class="tiny-dot"></span> 帝国边境星区 <b>/</b> M41.998</div><nav>${btn('行动记录','history','nav-button')}${btn('规则档案','help','nav-button')}${btn(fast?'极速 ◇':'动画 ◇','speed','nav-button',`aria-label="${fast?'切换标准动画':'切换极速动画'}"`)}${run&&view==='game'?btn(run.phase==='combat'?'结束并返回':'保存并返回',run.phase==='combat'?'retreat':'menu','nav-button exit',busy?'disabled':''):''}</nav></header>`;}
function home(){let current=saved();return `${header()}<main class="landing"><section class="intro"><div class="eyebrow"><span></span> 无光之域 · 灰烬巢都</div><div class="edition">WARHAMMER 40,000 <span>FAN GAME</span></div><h1>黑暗<span>远征</span></h1><p class="intro-line">在四十一千年的黑暗中，<br>让最后一道命令抵达。</p><div class="intro-rule"></div><p class="intro-copy">巢都失联。信号被亚空间风暴吞噬。<br>选择你的先锋，整备武装，深入灰烬圣堂。<br>每一张卡牌，都是生还的可能。</p><div class="mission-stats"><div><strong>07</strong><span>战团 / 职业</span></div><div><strong>03</strong><span>递进区域</span></div><div><strong>40+</strong><span>敌人 / 首领</span></div></div><div class="intro-foot">三段递进难度 <i>·</i> 混合派系牌堆</div></section><section class="deployment"><div class="section-title"><span>01 / 选择远征先锋</span><span>SELECT OPERATIVE</span></div><div class="class-grid">${Object.entries(D.classes).map(([id,c],i)=>`<button style="--chapter-color:${c.color}" class="class-card ${chosenClass===id?'selected':''}" data-action="class" data-id="${id}" aria-pressed="${chosenClass===id}"><div class="class-top"><span>0${i+1}</span><span>${chosenClass===id?'已选择 ◈':'◇'}</span></div><div class="class-art">${A.portrait(c.art)}</div><div class="class-caption"><small>${c.latin}</small><h2>${c.name}</h2><p>${c.subtitle}</p><div class="tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></button>`).join('')}</div><div class="deploy-brief"><div><span class="label">战术简报 / ${D.classes[chosenClass].name}</span><p>${D.classes[chosenClass].description}</p></div><span class="hp-badge">${D.classes[chosenClass].hp}<small>初始生命</small></span></div><div class="theater-note"><b>混合远征</b> · 派系敌人会在同一条牌堆中随机出现；区域只代表难度递进。</div><div class="difficulty-select">${Object.entries(D.difficulties).map(([id,d])=>btn(d.name,'difficulty',chosenDifficulty===id?'active':'',`data-id="${id}" title="${d.text}"`)).join('')}<small>${D.difficulties[chosenDifficulty].text}</small></div><div class="deploy-buttons">${btn('开始远征 <span>→</span>','deploy','primary deploy')}${current?btn('继续远征 <small>'+D.classes[current.classId].name+' · Lv.'+current.level+'</small>','continue','secondary continue'):''}</div><div class="deploy-note"><span class="tiny-dot"></span> ${current?'已检测到本地远征档案':'舰载系统在线 · 等待出发指令'}<span>约 40–70 分钟 / 局</span></div></section></main><footer class="site-footer"><span>玩法灵感：MAOU《卡牌冒险者》系列</span><span>非官方同人作品 · 原创矢量美术 · v2.2 · 混合远征</span><a href="legacy/index.html">旧版与旧存档 ↗</a><a href="README.md" target="_blank" rel="noopener">任务手册 ↗</a></footer>`;}
function bar(label,current,max,cls=''){return `<div class="stat-line ${cls}"><div><span>${label}</span><strong>${current}<em> / ${max}</em></strong></div><div class="meter"><i style="width:${Math.min(100,Math.max(0,current/max*100))}%"></i></div></div>`;}
function oldStatuses(u){return `<div class="statuses">${u.block?`<span>护盾 ${u.block}</span>`:''}${u.burn?`<span class="danger">焚烧 ${u.burn}</span>`:''}${u.suppress?`<span>压制 ${u.suppress}</span>`:''}${u.prepared?`<span>应对待命</span>`:''}</div>`;}
function statuses(u){const names={block:'护盾',burn:'焚烧',poison:'疫毒',suppress:'压制',mark:'标记',vulnerable:'破绽',weaken:'虚弱'};return `<div class="statuses">${Object.entries(names).filter(([id])=>u[id]).map(([id,name])=>`<span class="status-${id}" title="${statusText[id]}">${name} ${u[id]}</span>`).join('')}${u.prepared?'<span>应对待命</span>':''}</div>`;}
const statusText={poison:'回合开始损失层数生命，随后减1；净化清除，最多8层',block:'吸收直接伤害；己方下回合开始清零',burn:'回合开始失去层数对应生命，之后减一层',suppress:'每回合少抽1张',mark:'下次直接命中 +2伤害，消耗1层',vulnerable:'下次受击 +2伤害，消耗1层',weaken:'直接攻击 -2伤害，己方回合结束减1'};
function enemyPanel(){if(run.phase==='combat'||run.phase==='reward'){let u=run.battle.enemy,e=D.enemies[run.battle.enemyKey];return `<section class="side-section enemy-summary"><div class="section-kicker">敌方信号 <span>LV.${e.level}</span></div><div class="unit-heading"><div class="unit-thumb">${A.portrait(e.art)}</div><div><h3>${e.name}</h3><small>${D.factions[e.faction].name} · ${e.title.split(' · ')[1]}</small></div></div>${bar('生命',u.hp,u.maxHp,'health')}${bar('能源',u.energy,u.baseEnergy,'energy')}${statuses(u)}<p class="faction-tactic">${D.factions[e.faction].tactic}</p>${e.tactic?`<p class="enemy-tactic">战术：${e.tactic}</p>`:''}<div class="pile-buttons">${btn('牌堆 <b>'+u.draw.length+'</b>','hidden','pile')}${btn('坟场 <b>'+u.discard.length+'</b>','enemyDiscard','pile')}</div><div class="enemy-equips">${u.equipment.length?u.equipment.map(id=>`<span title="${esc(D.cards[id].text)}">${D.cards[id].name}</span>`).join(''):'装备区 · 暂无装备'}</div></section>`;}
 let en=G.encounter(run),def=en?(D.enemies[en.key]||D.events[en.key]):null;return `<section class="side-section encounter-summary"><div class="section-kicker">${en?'目标档案':'任务档案'}<span>01</span></div><div class="side-emblem">${art(en?def.art:'eagle')}</div><h3>${def?def.name:G.regions(run)[run.chapter].name}</h3><p>${def?def.description:D.campaigns[run.campaign].brief}</p>${en?.kind==='enemy'?`<div class="mini-metrics"><span>生命 <b>${Math.ceil(def.hp*D.difficulties[run.difficulty].hp)}</b></span><span>能源 <b>${def.energy}</b></span><span>等级 <b>${def.level}</b></span></div>`:''}</section>`;}
function detailContent(){let c=inspected&&D.cards[inspected.id];return c?`<div class="section-kicker">${types[c.type]} / ${c.attr}<span>${c.cost} 能源</span></div><h3>${c.name}</h3><p>${c.text}</p>${inspected.index!==undefined&&run.phase==='combat'?btn('弃置这张手牌','discard','text-button',`data-index="${inspected.index}"`):'<small>卡牌效果以当前规则档案为准</small>'}`:`<div class="section-kicker">战术终端 <span>◈</span></div><h3>${run.phase==='combat'?'保留手牌，规划下一步':'侦察先于进攻'}</h3><p>${run.phase==='combat'?'悬停或聚焦卡牌查看效果，点击出牌。右键可弃牌；应对牌会在受击时自动触发。':'选择一张遭遇卡查看行动。未选择的遭遇会留在桌面，直到你决定处理它们。'}</p>`;}
function playerPanel(){let c=D.classes[run.classId],u=run.phase==='combat'?run.battle.player:null;return `<section class="side-section player-summary"><div class="unit-heading"><div class="unit-thumb player">${A.portrait(c.art)}</div><div><small>远征先锋 <span class="level">LV.${run.level}</span></small><h3>${c.name}</h3></div></div>${bar('生命',u?u.hp:run.hp,run.maxHp,'health')}${bar(c.resource,u?u.energy:run.baseEnergy,run.baseEnergy,'energy')}${u?statuses(u):''}<div class="xp-row"><span>战功 ${run.xp} / ${run.nextLevel}</span><span class="credit">⟐ ${run.credits} <small>军需</small></span></div><div class="xp-meter"><i style="width:${run.xp/run.nextLevel*100}%"></i></div><div class="pile-buttons">${btn((u?'牌堆':'牌组')+' <b>'+(u?u.draw.length:run.deck.length)+'</b>','deck','pile')}${btn(u?'坟场 <b>'+u.discard.length+'</b>':'牌组检视 ↗',u?'discardPile':'deck','pile')}</div></section>`;}
function progress(){let chapter=G.regions(run)[run.chapter];return `<div class="mission-top"><div><span class="eyebrow">第 ${run.chapter+1} / 3 区域 · ${D.difficulties[run.difficulty].name}难度</span><h2>${chapter.name} <span>${chapter.subtitle}</span></h2></div><div class="progress-block"><div><span>远征推进</span><b>${String(run.resolved).padStart(2,'0')} <em>/ ${run.total}</em></b></div><div class="progress-ticks">${G.regions(run).map((c,i)=>`<i title="${c.name}" class="${i<=run.chapter?'done':''}"></i>`).join('')}</div></div></div>`;}
function facilityName(key){return D.facilityNames[run.campaign]?.[key]||D.events[key].name;}
function encounterCard(en,index){let enemy=en.kind==='enemy',d=enemy?D.enemies[en.key]:D.events[en.key];return `<button class="encounter-card ${enemy?'hostile':'facility'} ${run.selected===en.uid?'selected':''} ${en.key===G.regions(run)[run.chapter].boss?'boss':''}" data-action="encounter" data-id="${en.uid}"><div class="encounter-head"><span>${enemy?'⚔ 敌对信号':'◇ 可交互设施'}</span><b>${enemy?'LV.'+d.level:'EVENT'}</b></div><div class="encounter-art">${enemy?A.portrait(d.art):art(d.art)}<div class="art-index">${String(index+1).padStart(2,'0')}</div></div><div class="encounter-caption"><small>${enemy?D.factions[d.faction].name:d.subtitle}</small><h3>${enemy?d.name:facilityName(en.key)}</h3><div class="encounter-bottom"><span>${enemy?'生命 '+Math.ceil(d.hp*D.difficulties[run.difficulty].hp)+' · 军需 +'+d.credits:'探索此处'}</span><span>↗</span></div></div></button>`;}
function eventPanel(){let en=G.encounter(run);if(!en)return `<div class="action-panel idle"><div class="signal-icon">⌖</div><div><h3>选择下一次遭遇</h3><p>未处理的信号仍将保留。留意伤势，为最后的交战储备资源。</p></div><span class="small-label">等待指令</span></div>`;if(en.kind==='enemy'){let e=D.enemies[en.key];return `<div class="action-panel"><div><div class="label">交战许可 / LV.${e.level}</div><h3>${e.name}</h3><p>胜利获得 ${e.xp} 战功、${e.credits} 军需。战后伤势持续。</p></div>${btn(en.key===G.regions(run)[run.chapter].boss?'挑战区域首领 →':'进入战斗 →','battle','primary')}</div>`;}
 let e=D.events[en.key],choices='';if(en.key==='armory'){choices=G.armoryOffers(run).map(id=>`<button class="event-choice card-choice" data-action="event" data-choice="take" data-value="${id}">${art(D.cards[id].art)}<span><b>${D.cards[id].name}</b><small>${D.cards[id].text}</small></span></button>`).join('');}
 else if(en.key==='forge')choices=btn('选择强化卡牌 · 8 军需','forge','secondary');
 else if(en.key==='training')choices=D.talents[run.classId].filter(t=>!run.talents.includes(t.id)).map(t=>btn('<b>'+t.name+'</b><small>'+t.text+'</small>','event','event-choice',`data-choice="talent" data-value="${t.id}"`)).join('')||'<p>本职业专精已全部掌握。</p>';
 else if(en.key==='purge')choices=btn('选择要移除的牌 · 5 军需','purge','secondary');
 else if(en.key==='merchant')choices=`<button class="event-choice" data-action="event" data-choice="heal"><b>战地维护</b><small>5 军需 · 恢复4生命</small></button>`+['med','regroup','deflect','sight','crossfire','lastStand','requisitionKit'].map((id,i)=>`<button class="event-choice" data-action="event" data-choice="buy" data-value="${id}" title="${D.cards[id].text}"><b>${D.cards[id].name}</b><small>${[6,7,7,9,10,10,8][i]} 军需 · ${D.cards[id].cost} 费</small></button>`).join('');
 else choices=e.choices.filter(c=>c.id!=='leave').map(c=>`<button class="event-choice" data-action="event" data-choice="${c.id}"><b>${c.label}</b><small>${c.detail}</small></button>`).join('');
 return `<div class="event-actions"><div class="event-actions-title"><span>${e.name} <small>/ 选择行动</small></span>${btn('离开此处 →','event','text-button','data-choice="leave"')}</div><div class="event-options">${choices}</div></div>`;}
function backpack(){return `<div class="backpack"><div><span class="label">随身补给</span><small>${run.backpack.length} / ${D.RULES.backpackSlots}</small></div>${run.backpack.length?btn(art('med')+'<span>医疗包<small>恢复 6 生命 · 点击使用</small></span>','item','item-slot'): '<div class="item-slot empty">＋<span>背包为空<small>从补给站获取物资</small></span></div>'}</div>`;}
function exploration(){return `<div class="explore-area"><div class="field-label"><span><i class="tiny-dot"></i> ${run.bossSpawned?'区域首领已锁定':'探测到 '+run.field.length+' 处信号'}</span><span>遭遇牌堆 <b>${run.queue.length}</b></span></div><div class="encounter-row">${run.field.map(encounterCard).join('')}</div>${eventPanel()}</div><div class="explore-bottom">${backpack()}<div class="transmission"><span class="label">最新传讯</span><p>${esc(run.history.at(-1))}</p></div></div>`;}
function handCard(id,index){let c=D.cards[id],reason=G.canPlay(run,'player',index);return `<button class="hand-card ${c.type} ${reason?'unavailable':''}" data-action="play" data-index="${index}" data-card="${id}" aria-label="${c.name}，${c.cost}费，${c.text}${reason?'，'+reason:''}"><div class="hand-card-top"><b class="cost">${G.cost(run,run.battle.player,id)}</b><span>${types[c.type]}</span></div><div class="hand-art">${art(c.art)}</div><h4>${c.name}</h4><p>${c.text}</p><div class="hand-attr">${c.attr}</div></button>`;}
function revealedCard(last){if(!last)return '<div class="battle-idle"><span>✦</span><h3>选择卡牌或发动职业技能</h3><p>先标记、制造破绽，再组织连击；预留应对牌抵御反扑。</p></div>';let c=last.skill?D.skills[last.skill]:D.cards[last.card];return `<article class="reveal-card ${last.side}"><div><b>${c.cost} 能源</b><span>${last.side==='enemy'?'敌方出牌':'我方行动'}</span></div>${art(c.art)}<section><h3>${c.name}</h3><p>${c.text}</p></section></article>`;}
function skillPanel(){let u=run.battle.player,k=D.skills[run.classId],why=G.skillReason(run);return `<div class="skill-panel ${run.classId}"><div><span class="label">职业主动技能</span><h3>${k.name}</h3><p>${k.text}</p></div><div class="class-meter">${run.classId==='sister'?`虔诚 <b>${u.devotion} / 6</b>`:run.classId==='tech'?`热量 <b>${u.heat} / ${run.talents.includes('sink')?6:4}</b><small>超过上限：回合结束失去3生命</small>`:`<b>${D.classes[run.classId].tags[0]}</b><small>${D.classes[run.classId].passiveText||''}</small>`}</div>${btn(why||'发动技能 →','skill','secondary',why||busy?'disabled':'')}</div>`;}
function combat(){let b=run.battle,u=b.player,v=b.enemy;return `<div class="battle-area"><div class="duel-banner enemy"><span>敌方 · ${v.name}</span><b>生命 ${v.hp}/${v.maxHp}　能源 ${v.energy}/${v.baseEnergy}</b>${statuses(v)}</div><div class="enemy-hand" aria-label="敌方手牌 ${v.hand.length} 张">${v.hand.map((_,i)=>`<div class="card-back" style="--tilt:${(i-(v.hand.length-1)/2)*3}deg">${art('eagle')}</div>`).join('')}<span>敌方手牌 · ${v.hand.length}　/ 第 ${b.round} 回合</span></div><div class="battle-center ${busy?'resolving':''}">${revealedCard(b.last)}<div class="resolution-text"><span class="turn-label">${busy?'逐项结算中':b.active==='enemy'?'敌方回合':'你的回合'}</span><h3>${esc(playback||b.log.at(-1)||'武装就绪')}</h3>${b.reaction?`<div class="reaction-pop">${art(D.cards[b.reaction.card].art)}<span>应对触发<br><b>${D.cards[b.reaction.card].name}</b></span></div>`:''}<div class="battle-feed">${b.log.slice(-2).map(t=>`<p>${esc(t)}</p>`).join('')}</div></div></div><div class="duel-banner player"><span>我方 · ${u.name}</span><b>生命 ${u.hp}/${u.maxHp}　能源 ${u.energy}/${u.baseEnergy}</b>${statuses(u)}</div>${skillPanel()}<div class="combat-controls"><div class="equipment-row"><span class="label">装备 ${u.equipment.length} / 2</span>${u.equipment.map((id,i)=>btn(art(D.cards[id].art)+'<span>'+D.cards[id].name+'<small>点击卸下</small></span>','unequip','equipped',`data-index="${i}" title="${D.cards[id].text}"`)).join('')}${u.prepared?`<span class="prepared">◇ ${D.cards[u.prepared].name}待命</span>`:''}</div><div class="turn-control">${btn(busy?'正在交战…':'结束回合 →','end','primary',busy?'disabled':'')}<small>保留手牌 · 下回合抽 2 张</small></div></div><div class="hand-zone"><div class="hand-meta"><span>战术手牌 <b>${u.hand.length} / 10</b></span>${btn(discardMode?'取消弃牌':'弃牌模式','discardMode','text-button')}<span>${discardMode?'点击手牌弃置':'点击出牌 · 右键弃置'}</span></div><div class="hand-row">${u.hand.length?u.hand.map(handCard).join(''):'<div class="empty-hand">手牌已用尽。可以发动技能，或结束回合。</div>'}</div></div></div><div class="battle-footer">${btn('行动记录 ↗','history','text-button')}${btn('医疗包 '+run.backpack.length+' / 1','item','text-button',!run.backpack.length?'disabled':'')}<span class="small-label">${run.talents.map(id=>D.talents[run.classId].find(t=>t.id===id)?.name).join(' · ')||'尚未选择专精'}</span></div>`;}
function reward(){return `<div class="reward-screen"><div class="eyebrow">${run.reward.chapterClear?'区域首领已击败':'交战胜利'}</div><h2>${run.reward.chapterClear?'通路已经打开':'选择你的战利品'}</h2><p>获得 ${run.reward.xp} 战功、${run.reward.credits} 军需。生命 ${run.hp}/${run.maxHp}。</p><div class="loot-row">${run.reward.choices.map(id=>`<button class="loot-card" data-action="loot" data-id="${id}" ${run.reward.taken?'disabled':''}>${art(D.cards[id].art)}<h3>${D.cards[id].name}</h3><small>${D.cards[id].cost} 费 · ${types[D.cards[id].type]}</small><p>${D.cards[id].text}</p></button>`).join('')}</div><p>${run.reward.taken?'卡牌已加入牌组。':'可以选一张加入牌组，也可以跳过，保持牌组精简。'}</p>${btn(run.reward.chapterClear?'前往下一区域 →':run.reward.taken?'继续远征 →':'跳过并继续 →','claim','primary')}<div class="field-dressing">${btn('战地维护 · 6 军需 → 恢复 5 生命','rewardDressing','secondary',run.reward.fieldDressing||run.hp>=run.maxHp||run.credits<6?'disabled':'')}<small>${run.reward.fieldDressing?'本次战后整备已使用':run.hp>=run.maxHp?'生命已满':run.credits<6?'军需不足（需要6）':'战斗胜利后可进行一次，适合首领前整备'}</small></div><small>${run.reward.chapterClear?'转移区域时恢复8生命，其他牌组与成长保留':'伤势保留，奖励不会重复领取'}</small></div>`;}
function endScreen(){let win=run.phase==='victory';return `<div class="ending ${win?'victory':'defeat'}"><div class="ending-art">${art(win?'eagle':'skull')}</div><div class="eyebrow">${win?'MISSION ACCOMPLISHED':'SIGNAL LOST'}</div><h1>${win?'长夜之中，使命已达。':'信号，归于沉寂。'}</h1><p>${win?D.campaigns[run.campaign].ending:'你的最后一次传讯停在灰烬深处。远征失败，但下一名先锋将接过这道命令。'}</p><div class="ending-stats"><div><strong>${run.level}</strong><span>先锋等级</span></div><div><strong>${run.battlesWon}</strong><span>击败敌人</span></div><div><strong>${run.resolved}/${run.total}</strong><span>完成遭遇</span></div><div><strong>${run.credits}</strong><span>剩余军需</span></div></div><div class="ending-buttons">${win?btn('新的远征 →','new','primary'):`${btn('回到战斗前','retreat','primary')} ${btn('放弃本局 · 新的远征 →','new','secondary')}`}${btn('查看行动记录','history','secondary')}</div><small>每一场远征，都是一次新的选择。</small></div>`;}
function gameView(){if(['victory','defeat'].includes(run.phase))return `${header()}<main class="end-main">${endScreen()}</main>${footer()}`;return `${header()}<main class="game-layout"><aside class="sidebar">${enemyPanel()}<section class="side-section detail-panel" id="card-detail">${detailContent()}</section>${playerPanel()}</aside><section class="tabletop">${progress()}${run.phase==='combat'?combat():run.phase==='reward'?reward():exploration()}</section></main>${footer()}`;}
function footer(){return `<footer class="game-footer"><span><i class="tiny-dot"></i> ${storageAvailable?'进度已自动保存至本机':'存档不可用 · 请勿关闭页面'}</span><span>灰烬远征 / 非官方同人作品</span><span>${run.phase==='combat'?'战斗进行中':run.phase==='adventure'?'等待行动指令':'任务状态已更新'}</span></footer>`;}
// Preserve existing nodes so each log entry does not restart every card animation.
function patchNode(current,next){
 if(current.isEqualNode(next))return;
 if(current.nodeType!==next.nodeType||current.nodeName!==next.nodeName){current.replaceWith(next);return;}
 if(current.nodeType===Node.TEXT_NODE){current.nodeValue=next.nodeValue;return;}
 if(current.nodeType!==Node.ELEMENT_NODE)return;
 for(const attr of [...current.attributes])if(!next.hasAttribute(attr.name))current.removeAttribute(attr.name);
 for(const attr of [...next.attributes])if(current.getAttribute(attr.name)!==attr.value)current.setAttribute(attr.name,attr.value);
 const oldChildren=[...current.childNodes],newChildren=[...next.childNodes];
 for(let i=0;i<Math.max(oldChildren.length,newChildren.length);i++){
  if(!newChildren[i])oldChildren[i].remove();else if(!oldChildren[i])current.append(newChildren[i]);else patchNode(oldChildren[i],newChildren[i]);
 }
}
function render(){document.body.classList.toggle('fast',fast);document.body.classList.toggle('resolving-action',busy);const template=document.createElement('template');template.innerHTML=view==='home'?home():gameView();const next=document.createElement('div');next.id='app';next.append(template.content);patchNode($('#app'),next);}
function playRevealMotion(){
 if(fast||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const card=$('.reveal-card');if(!card)return;
 card.getAnimations().forEach(animation=>animation.cancel());
 card.animate([{opacity:0,transform:'translateY('+ (run.battle.last?.side==='enemy'?'-8':'8') +'px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'cubic-bezier(.2,.7,.3,1)'});
}
function openModal(title,content,cls=''){lastFocus=document.activeElement;modal=title;$('#modal-root').innerHTML=`<div class="modal-backdrop" data-action="closeBackdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="${title}"><div class="modal-head"><div><small>舰载终端 / ARCHIVE</small><h2>${title}</h2></div>${btn('×','close','close',`aria-label="关闭${title}"`)}</div><div class="modal-content">${content}</div></section></div>`;$('.modal .close').focus();}
function closeModal(){modal='';$('#modal-root').innerHTML='';if(lastFocus?.isConnected)lastFocus.focus();}
function cardList(ids,mode){if(!ids.length)return '<p class="modal-empty">这里暂时没有卡牌。</p>';return `<div class="archive-cards">${ids.map((id,index)=>{let c=D.cards[id];return `<article class="archive-card">${art(c.art)}<div><small>${c.cost} 费 / ${types[c.type]} / ${c.attr}</small><h3>${c.name}</h3><p>${c.text}</p>${mode==='remove'?btn('移除 · 5 军需','event','secondary small',`data-choice="remove" data-value="${index}"`):''}</div></article>`;}).join('')}</div>`;}
function help(){openModal('战术档案 · 战区扩展',`<div class="rules-intro"><b>混合远征 · 七种先锋</b><p>三段递进难度，派系敌人混编进入同一远征。区域首领从对应首领池中随机出现。保留手牌，敌我共用卡牌规则。默认老兵难度。</p></div><div class="help-grid"><section><h3>回合与战斗过程</h3><p>起手3张，之后每回合抽2，上限10；结束回合保留手牌。能源在己方回合开始重置。敌方会逐张展示出牌、应对、伤害与状态，顶部可切换极速。战斗超过12回合后，敌方每两回合提高1点火力。</p></section><section><h3>派系情报</h3>${Object.values(D.factions).map(f=>`<p><b>${f.name}</b>：${f.tactic}。</p>`).join('')}</section><section><h3>标记与负面状态</h3>${Object.entries(statusText).map(([id,t])=>`<p><b>${{block:'护盾',burn:'焚烧',poison:'疫毒',suppress:'压制',mark:'标记',vulnerable:'破绽',weaken:'虚弱'}[id]}</b>：${t}。</p>`).join('')}</section><section><h3>战团与职业</h3>${Object.entries(D.classes).map(([id,c])=>`<p><b>${c.name}</b>：${c.description}<br>技能：${D.skills[id].name} — ${D.skills[id].text}</p>`).join('')}</section><section><h3>成长与构筑</h3><p>战后从3张战利品中选择1张或跳过。军械库补充职业牌；强化台花8军需强化一张攻击牌；专精舱选择永久被动。每区有独立牌堆和首领，转移区域恢复8生命。升级生命上限+2、恢复2；基础能源在3级、6级提升，上限3。</p><p>双方有2个装备位，自动应对每次受击触发一张，反射不无限连锁。神甫超过热量安全上限时，回合结束失去3生命、热量降至2。</p></section></div><details class="provenance"><summary>版本与参考边界</summary><p>混合远征加入血天使、帝国之拳、火蜥蜴、太空野狼与四条派系战区。采用M41战团身份，保留军团传承。疫毒为战斗状态，不新增支付资源。V2为本次授权扩展：新增职业技能、标记、破绽、虚弱、虔诚、热量、连射、回收、强化、专精、三域与难度选择。这些属于本作设计，并非宣称原作已有机制。旧版存档保留在旧版入口。</p></details>`,'wide');}
async function animateAction(fn){busy=true;inspected=null;const finalState=structuredClone(run);const output=G.capture(finalState,()=>fn(finalState));if(output.result?.ok===false){busy=false;toast(output.result.reason);return;}run=finalState;save();try{if(!fast){for(const frame of output.frames){if(fast)break;run=frame.state;playback=frame.text;render();if(frame.reveal)playRevealMotion();await new Promise(resolve=>setTimeout(resolve,frame.reveal?780:320));}}}finally{run=finalState;playback=null;busy=false;render();}}
function inspect(el){let id=el.dataset.card;if(!id)return;inspected={id,index:Number(el.dataset.index)};let panel=$('#card-detail');if(panel)panel.innerHTML=detailContent();}
async function action(e){let el=e.target.closest('[data-action]');if(!el)return;let ac=el.dataset.action;if(busy&&!['history','help','close','speed'].includes(ac))return;
 switch(ac){
 case 'difficulty':chosenDifficulty=el.dataset.id;render();break;
 case 'class':chosenClass=el.dataset.id;render();break;
 case 'deploy':if(saved()&&!['victory','defeat'].includes(saved().phase))openModal('开始新的远征',`<p>本机已有一份进行中的远征。开始新远征将替换这份存档。</p><div class="modal-actions">${btn('返回','close','secondary')}${btn('开始新远征','confirmDeploy','primary')}</div>`);else deploy();break;
 case 'confirmDeploy':closeModal();deploy();break;
 case 'continue':run=saved();if(run){view='game';render();}else toast('没有有效的远征存档。');break;
 case 'home':case 'menu':if(run)save();view='home';render();break;
 case 'new':view='home';render();break;
 case 'encounter':G.select(run,el.dataset.id);inspected=null;save();render();break;
 case 'retreat':{const result=G.returnToAdventure(run);if(!result.ok){toast(result.reason);break;}discardMode=false;inspected=null;playback=null;save();render();toast(result.restored?'已回到战斗前，生命与补给恢复至交战前状态。':'已返回冒险页面。旧存档没有战前记录，保留当前伤势与补给。');break;}
 case 'battle':discardMode=false;G.beginBattle(run);inspected=null;save();render();break;
 case 'discardMode':discardMode=!discardMode;render();break;
 case 'play':{if(discardMode){G.discard(run,Number(el.dataset.index));discardMode=false;inspected=null;save();render();toast('卡牌已弃置到坟场。');break;}await animateAction(state=>G.playCard(state,'player',Number(el.dataset.index)));break;}
 case 'skill':await animateAction(state=>G.useSkill(state));break;
 case 'end':discardMode=false;await animateAction(state=>G.endTurn(state));break;
 case 'loot':if(G.chooseReward(run,el.dataset.id)){save();render();}break;
 case 'forge':openModal('强化一张攻击牌',`<p>8 军需 / 基础伤害 +1。当前军需 ${run.credits}</p><div class="archive-cards">${run.deck.map((id,i)=>D.upgrades[id]?`<article class="archive-card">${art(D.cards[id].art)}<div><h3>${D.cards[id].name}</h3><p>${D.cards[id].text}</p>${btn('强化 · 8 军需','event','secondary',`data-choice="upgrade" data-value="${i}"`)}</div></article>`:'').join('')}</div>`,'wide');break;
 case 'discard':G.discard(run,Number(el.dataset.index));inspected=null;save();render();break;
 case 'unequip':G.unequip(run,Number(el.dataset.index));save();render();break;
 case 'item':{let r=G.useItem(run);if(!r.ok)toast(r.reason);else{save();render();toast('医疗包已使用，恢复最多 6 点生命。');}break;}
 case 'event':{let value=['remove','upgrade'].includes(el.dataset.choice)?Number(el.dataset.value):el.dataset.value;let result=G.eventAction(run,el.dataset.choice,value);if(!result.ok){toast(result.reason||'此行动暂不可执行');return;}closeModal();inspected=null;save();render();break;}
 case 'purge':openModal('战术重整 · 选择移除',`<p>花费 5 军需，移除本次远征中的一张牌。至少保留 5 张。当前军需：${run.credits}</p>${cardList(run.deck,'remove')}`,'wide');break;
 case 'claim':G.claimReward(run);inspected=null;save();render();break;
 case 'rewardDressing':{let r=G.rewardDressing(run);if(!r.ok){toast(r.reason);break;}save();render();toast('战地维护完成，恢复 '+r.amount+' 生命。');break;}
 case 'deck':openModal(run.phase==='combat'?'我方剩余牌堆（不按抽取顺序）':'本次远征牌组',cardList(run.phase==='combat'?[...run.battle.player.draw].sort():run.deck),'wide');break;
 case 'discardPile':openModal('我方坟场',cardList(run.battle.player.discard),'wide');break;
 case 'enemyDiscard':openModal('敌方坟场 · 已公开卡牌',cardList(run.battle.enemy.discard),'wide');break;
 case 'hidden':toast('敌方牌堆内容不可见。你可以查看已公开的坟场。');break;
 case 'help':help();break;
 case 'history':openModal('行动记录',run?`<ol class="history-list">${run.history.map((t,i)=>`<li><span>${String(i+1).padStart(3,'0')}</span>${esc(t)}</li>`).join('')}</ol>`:'<p class="modal-empty">远征尚未开始。等待第一条指令。</p>');$('.modal-content').scrollTop=$('.modal-content').scrollHeight;break;
 case 'speed':fast=!fast;try{localStorage.setItem('dark-expedition.fast.v2',fast?'1':'0');}catch{}render();toast(fast?'极速模式：跳过行动等待与动画。':'标准模式：显示简洁的行动反馈。');break;
 case 'close':closeModal();break;
 case 'closeBackdrop':if(e.target===el)closeModal();break;
 }
}
function deploy(){discardMode=false;run=G.newRun(chosenClass,Date.now(),chosenDifficulty,'crusade');view='game';inspected=null;save();render();openModal('远征须知',`<div class="tutorial"><p><b>01 · 选择遭遇</b>桌面同时保留三张敌人或设施卡。先查看目标，再决定是否交战。</p><p><b>02 · 组合出牌</b>起手三张，点击使用。零费攻击与付费武器可以组合，能源不足时使用战术整备。</p><p><b>03 · 留牌应对</b>结束回合保留手牌，下回合抽两张。力场应对牌在受击时自动触发。</p><p><b>04 · 保存实力</b>伤势跨战斗保留。补给站回血，军械库获得新牌。穿越三个区域，选择专精与强化卡牌，击败三个首领。</p></div><div class="modal-actions"><p><b>05 · 发动职业技能</b>${D.classes[chosenClass].description} ${D.skills[chosenClass].text}</p>${btn('明白，开始行动 →','close','primary')}</div>`);}
document.addEventListener('click',action);
document.addEventListener('mouseover',e=>{let el=e.target.closest('[data-card]');if(el)inspect(el);});
document.addEventListener('focusin',e=>{let el=e.target.closest('[data-card]');if(el)inspect(el);});
document.addEventListener('contextmenu',e=>{let el=e.target.closest('[data-action="play"]');if(!el||busy||modal)return;e.preventDefault();G.discard(run,Number(el.dataset.index));inspected=null;save();render();toast('卡牌已弃置到坟场。');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal){closeModal();return;}if(e.key==='Tab'&&modal){const items=Array.from(document.querySelectorAll('.modal button,.modal a,.modal summary')).filter(x=>!x.disabled);let first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
render();
