'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('../engine'),D=require('../data');
function battle(id='marine',seed=12,difficulty='story'){let s=G.newRun(id,seed,difficulty);G.select(s,s.field.find(e=>e.kind==='enemy').uid);G.beginBattle(s);return s;}
function setup(s,p,e=[]){s.battle.player.hand=p;s.battle.enemy.hand=e;s.battle.enemy.draw=[];s.battle.enemy.discard=[];}
test('three-region content and class decks are complete',()=>{assert.equal(D.chapters.length,3);assert.ok(Object.keys(D.cards).filter(x=>!D.cards[x].upgraded).length>=40);for(const cls of Object.keys(D.classes)){const s=G.newRun(cls,123);assert.equal(s.total,36);assert.equal(s.field.length,3);assert.equal(s.deck.length,10);assert.ok(s.deck.every(x=>D.cards[x]));}for(const c of D.chapters){assert.ok(D.enemies[c.boss]);for(const id of c.cards)assert.ok(D.enemies[id]||D.events[id]);}});
test('rejected cards and locked actions do not spend energy',()=>{let s=battle();setup(s,['overload']);let before=JSON.stringify(s);assert.equal(G.playCard(s,'player',0).ok,false);assert.equal(JSON.stringify(s),before);s.battle.active='enemy';assert.equal(G.useSkill(s).ok,false);assert.equal(G.useItem(s).ok,false);});
test('resources overflow temporarily and unplayed hand persists',()=>{let s=battle();setup(s,['regroup','overload']);G.playCard(s,'player',0);assert.equal(s.battle.player.energy,3);s.battle.player.draw=['guard','strike'];G.endTurn(s);assert.equal(s.battle.player.energy,1);assert.deepEqual(s.battle.player.hand,['overload','guard','strike']);});
test('draw recycles discard without exceeding hand limit',()=>{let s=battle(),u=s.battle.player;u.hand=Array(9).fill('strike');u.draw=[];u.discard=['med','guard'];G.draw(s,u,5);assert.equal(u.hand.length,10);assert.equal(u.draw.length,1);});
test('marks interact with separate hits and marine first-hit bonus',()=>{let s=battle();setup(s,['burst']);s.battle.enemy.hp=30;s.battle.enemy.mark=2;G.playCard(s,'player',0);assert.equal(s.battle.enemy.hp,21);assert.equal(s.battle.enemy.mark,0);});
test('vulnerability and weakness combine consistently',()=>{let s=battle();setup(s,['bolter']);s.battle.player.weaken=2;s.battle.enemy.vulnerable=1;let hp=s.battle.enemy.hp;G.playCard(s,'player',0);assert.equal(s.battle.enemy.hp,hp-4);assert.equal(s.battle.enemy.vulnerable,0);});
test('only one reaction per hit and reflected damage does not chain',()=>{let s=battle();setup(s,['strike','deflect'],['deflect','deflect']);let hp=s.hp;G.playCard(s,'player',0);assert.equal(s.hp,hp-2);assert.equal(s.battle.enemy.hand.length,1);assert.equal(s.battle.player.hand.length,1);});
test('emergency ward absorbs instead of reflecting',()=>{let s=battle();setup(s,['bolter'],['ward']);let hp=s.battle.enemy.hp;G.playCard(s,'player',0);assert.equal(s.battle.enemy.hp,hp);assert.equal(s.hp,s.maxHp);});
test('marine skill marks, draws and respects cooldown',()=>{let s=battle();setup(s,[]);assert.ok(G.useSkill(s).ok);assert.equal(s.battle.enemy.mark,2);assert.equal(s.battle.player.hand.length,1);assert.equal(G.useSkill(s).ok,false);G.endTurn(s);assert.equal(s.battle.player.skillCd,1);G.endTurn(s);assert.equal(s.battle.player.skillCd,0);});
test('sister gains devotion and spends it on heal and fire',()=>{let s=battle('sister');setup(s,['litany']);G.playCard(s,'player',0);assert.equal(s.battle.player.devotion,3);s.battle.player.hp-=7;assert.ok(G.useSkill(s).ok);assert.equal(s.battle.player.devotion,0);assert.equal(s.battle.enemy.burn,2);assert.equal(s.hp,s.maxHp-3);});
test('tech heat vent and overheat damage work separately',()=>{let s=battle('tech');setup(s,['arc']);s.battle.player.heat=4;G.playCard(s,'player',0);assert.equal(s.battle.player.heat,5);let hp=s.hp;G.endTurn(s);assert.equal(s.hp,hp-3);assert.equal(s.battle.player.heat,2);G.useSkill(s);assert.equal(s.battle.player.block,4);assert.equal(s.battle.player.heat,0);});
test('heat discharge scales and resets heat',()=>{let s=battle('tech');setup(s,['discharge']);s.battle.player.heat=4;let hp=s.battle.enemy.hp;G.playCard(s,'player',0);assert.equal(s.battle.enemy.hp,hp-7);assert.equal(s.battle.player.heat,0);});
test('recycling retrieves last eligible card without duplicating itself',()=>{let s=battle('tech');setup(s,['recycle']);s.battle.player.discard=['bolter','recycle'];G.playCard(s,'player',0);assert.deepEqual(s.battle.player.hand,['bolter']);assert.deepEqual(s.battle.player.discard,['recycle','recycle']);});
test('equipment slots, drone and cleanser resolve',()=>{let s=battle();setup(s,['armor']);s.battle.player.equipment=['drone','servitor'];assert.equal(G.playCard(s,'player',0).ok,false);let hp=s.battle.enemy.hp;G.endTurn(s);assert.equal(s.battle.enemy.hp,hp-2);G.unequip(s,0);assert.ok(s.battle.player.discard.includes('drone'));setup(s,['absolution']);s.battle.player.burn=3;s.battle.player.weaken=2;s.battle.player.vulnerable=2;G.playCard(s,'player',0);assert.equal(s.battle.player.burn+s.battle.player.weaken+s.battle.player.vulnerable,0);});
test('animation captures reveal before damage, independent frames and same final state',()=>{let s=battle();setup(s,['bolter'],['deflect']);let hp=s.battle.enemy.hp;let {frames}=G.capture(s,()=>G.playCard(s,'player',0));assert.ok(frames.length>=4);let reveal=frames.find(f=>f.reveal);assert.equal(reveal.state.battle.enemy.hp,hp);assert.ok(frames.some(f=>f.text.includes('触发')));assert.ok(frames.some(f=>f.text.includes('直接命中')));assert.equal(reveal.state.battle.enemy.hp,hp);assert.ok(G.restore(JSON.stringify(s)));});
test('enemy turn is observable card-by-card and pays costs',()=>{let s=battle();setup(s,[],['regroup','bolter','strike']);let {frames}=G.capture(s,()=>G.endTurn(s));assert.ok(frames.filter(f=>f.reveal).length>=2);assert.equal(s.battle.active,'player');assert.ok(s.battle.enemy.discard.includes('bolter'));assert.ok(G.restore(s));});
test('reward granted once, loot optional and cannot duplicate',()=>{let s=battle();setup(s,['strike']);s.battle.enemy.hp=2;G.playCard(s,'player',0);assert.equal(s.phase,'reward');let cash=s.credits,n=s.deck.length;G.checkOutcome(s);assert.equal(s.credits,cash);let card=s.reward.choices[0];assert.ok(G.chooseReward(s,card));assert.equal(G.chooseReward(s,card),false);assert.equal(s.deck.length,n+1);G.claimReward(s);assert.equal(G.claimReward(s),false);});
function event(s,key){let e=[...s.field,...s.queue].find(x=>x.key===key);if(!e){e={uid:'test-'+key,key,kind:'event'};}else s.queue=s.queue.filter(x=>x.uid!==e.uid);if(!s.field.includes(e))s.field.push(e);G.select(s,e.uid);}
test('forging and specialization persist through saves',()=>{let s=G.newRun('marine',4);event(s,'forge');G.eventAction(s,'upgrade',0);assert.equal(s.deck[0],'strike_plus');assert.equal(s.credits,17);event(s,'training');G.eventAction(s,'talent','precision');let saved=G.restore(s);assert.deepEqual(saved.talents,['precision']);assert.equal(saved.deck[0],'strike_plus');});
test('chapter boss advances region without ending run',()=>{let s=battle();s.battle.enemyKey='officer';s.battle.enemy.hp=1;setup(s,['strike']);G.playCard(s,'player',0);assert.equal(s.phase,'reward');assert.ok(s.reward.chapterClear);G.claimReward(s);assert.equal(s.chapter,1);assert.equal(s.phase,'adventure');assert.equal(s.field[0].key,'husk');});
test('difficulty scaling, burn defeat and malformed saves',()=>{assert.ok(battle('marine',1,'nightmare').battle.enemy.hp>battle('marine',1,'story').battle.enemy.hp);let s=battle();setup(s,[]);s.battle.player.hp=1;s.battle.player.burn=2;G.endTurn(s);assert.equal(s.phase,'defeat');for(let raw of ['invalid','{}','{"version":1}',null])assert.equal(G.restore(raw),null);});
test('tech vent repairs from heat and removes marks without extra energy',()=>{let s=battle('tech'),u=s.battle.player;setup(s,[]);u.hp-=5;u.heat=3;u.mark=2;let energy=u.energy;G.useSkill(s);assert.equal(u.hp,u.maxHp-2);assert.equal(u.mark,0);assert.equal(u.block,5);assert.equal(u.energy,energy);assert.equal(u.skillCd,2);});
test('boss phase triggers once and remains stable across turns',()=>{let s=battle();setup(s,[]);s.battle.enemyKey='boss';let e=s.battle.enemy;e.hp=6;e.maxHp=16;G.endTurn(s);assert.equal(e.enraged,true);assert.equal(e.block,6);G.endTurn(s);assert.equal(e.block,0);});
test('three complete veteran campaigns survive periodic save and restore',()=>{const simulate=require('./simulate');for(let [cls,seed] of [['marine',387276917],['sister',2654435761],['tech',2654435761]]){let s=simulate(cls,seed);assert.ok(['victory','defeat'].includes(s.phase),cls);assert.ok(s.resolved>=0);assert.ok(s.chapter>=0);assert.ok(s.battlesWon>=0);assert.ok(G.restore(s));}});
test('return restores the exact pre-battle adventure after saving and consuming items',()=>{let s=G.newRun('marine',34);s.hp-=8;G.select(s,s.field.find(e=>e.kind==='enemy').uid);let before=structuredClone(s);G.beginBattle(s);let hand=[...s.battle.player.hand];G.useItem(s);G.endTurn(s);s=G.restore(s);assert.ok(G.returnToAdventure(s).restored);assert.deepEqual(s,before);G.beginBattle(s);assert.deepEqual(s.battle.player.hand,hand);});
test('legacy combat return keeps wounds, encounter and rewards intact; cannot undo wins',()=>{let s=battle();delete s.beforeBattle;let hp=s.hp,cash=s.credits,uid=s.selected;assert.equal(G.returnToAdventure(s).restored,false);assert.equal(s.phase,'adventure');assert.equal(s.hp,hp);assert.equal(s.credits,cash);assert.equal(s.selected,uid);assert.ok(s.field.some(e=>e.uid===uid));assert.equal(G.returnToAdventure(s).ok,false);G.beginBattle(s);s.phase='reward';assert.equal(G.returnToAdventure(s).ok,false);});
test('faction campaigns use dedicated enemies and preserve three chapter structure',()=>{for(const id of ['nurgle','khorne','necron','ork']){let s=G.newRun('blood',99,'story',id);assert.equal(s.campaign,id);assert.equal(s.total,33);assert.equal(s.field[0].key,D.campaigns[id].chapters[0].cards[0]);let enemy=D.enemies[s.field[0].key];assert.equal(enemy.faction,id);assert.equal(D.campaigns[id].chapters.length,3);assert.ok(D.factions[id]);}});
test('faction cards and statuses have real engine behavior',()=>{let s=G.newRun('blood',12,'story','nurgle'),en=s.field.find(e=>e.kind==='enemy');G.select(s,en.uid);G.beginBattle(s);s.battle.enemy.hand=['rotBlade'];s.battle.enemy.energy=1;s.battle.active='enemy';G.playCard(s,'enemy',0);assert.equal(s.battle.player.poison,2);let hp=s.battle.player.hp;s.battle.active='player';G.endTurn(s);assert.equal(s.battle.player.hp,hp-2);s=G.newRun('fists',12,'story','crusade');G.select(s,s.field.find(e=>e.kind==='enemy').uid);G.beginBattle(s);assert.equal(s.battle.player.block,2);G.endTurn(s);assert.equal(s.battle.player.block,2);});
test('new chapter factions restore safely',()=>{for(const id of ['blood','fists','salamander','wolf']){let s=G.newRun(id,7,'veteran');assert.ok(G.restore(s));assert.equal(s.classId,id);}});
test('new tactical cards create meaningful combos and status conversion',()=>{let s=battle(),u=s.battle.player,v=s.battle.enemy;setup(s,['designate','markBurst','purgeFlame','lastStand']);s.battle.player.energy=3;G.playCard(s,'player',0);assert.equal(v.mark,2);let hp=v.hp;G.playCard(s,'player',0);assert.ok(v.hp<hp);v.burn=3;v.poison=2;v.weaken=2;G.playCard(s,'player',0);assert.equal(v.burn+v.poison+v.weaken,0);});
test('merchant offers card variety and a real paid maintenance action',()=>{let s=G.newRun('marine',6);let e={uid:'merchant-test',key:'merchant',kind:'event'};s.field=[e];s.selected=e.uid;let cash=s.credits;assert.ok(G.eventAction(s,'heal').ok);assert.equal(s.credits,cash-5);assert.equal(s.phase,'adventure');});

test('primarch choices survive reload, consume one encounter and cannot duplicate',()=>{let s=G.newRun('marine',42);s.field=[{uid:'archive',kind:'event',key:'primarch'}];s.selected='archive';const offers=G.primarchOffers(s);assert.equal(offers.length,3);assert.deepEqual(G.primarchOffers(G.restore(s)),offers);let id=offers[0],count=s.deck.length;assert.equal(G.eventAction(s,'inherit','invalid').ok,false);assert.equal(G.eventAction(s,'inherit',id).ok,true);assert.equal(s.deck.length,count+1);assert.ok(s.deck.includes(D.primarchs[id].card));assert.deepEqual(G.restore(s).legacies,[id]);assert.equal(G.eventAction(s,'inherit',id).ok,false);assert.ok(!G.primarchOffers(s).includes(id));});
test('all nine legacies apply only on opening and roll back exactly after defeat',()=>{for(const [id,d] of Object.entries(D.primarchs)){let s=G.newRun('marine',42);s.legacies=[id];s.hp=10;G.select(s,s.field.find(e=>e.kind==='enemy').uid);let before=structuredClone(s);G.beginBattle(s);let p=s.battle.player,e=s.battle.enemy,o=d.opening;assert.equal(p.hp,10+(o.heal||0),id);assert.equal(p.hand.length,3+(o.draw||0),id);assert.equal(p.block,o.block||0,id);assert.equal(p.energy,1+(o.energy||0),id);assert.equal(e.mark,o.mark||0,id);assert.equal(e.vulnerable,o.vulnerable||0,id);assert.equal(e.weaken,o.weaken||0,id);s.battle.player.hp=0;G.checkOutcome(s);s=G.restore(s);assert.equal(G.returnToAdventure(s).ok,true);assert.deepEqual(s,before);}});
test('legacy saves are accepted and corrupt legacy ids rejected',()=>{let s=G.newRun('tech',42);delete s.legacies;assert.ok(G.restore(s));s.legacies=['invalid'];assert.equal(G.restore(s),null);s.legacies=['dorn','dorn'];assert.equal(G.restore(s),null);});
test('legacy cards use normal costs, effects and reaction rules',()=>{let s=battle();setup(s,['ravenStrike']);s.battle.enemy.mark=1;s.battle.enemy.hp=30;s.battle.enemy.maxHp=30;s.battle.player.energy=0;assert.equal(G.playCard(s,'player',0).ok,false);s.battle.player.energy=1;G.playCard(s,'player',0);assert.equal(s.battle.enemy.hp,21);assert.ok(s.battle.player.discard.includes('ravenStrike'));s=battle();setup(s,['strike'],['lionGuard']);s.battle.enemy.energy=1;G.playCard(s,'player',0);assert.equal(s.battle.enemy.energy,0);assert.ok(s.battle.enemy.discard.includes('lionGuard'));assert.equal(s.battle.enemy.block,3);});
