'use strict';
const D=GAME_DATA,G=GAME,A=ART,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE_KEY='dark-expedition.save.v1';let run=null,chosenClass='marine',view='home',inspected=null,modal='',busy=false,fast=false,lastFocus=null,storageAvailable=true,discardMode=false;
try{fast=localStorage.getItem('dark-expedition.fast')==='1';}catch{storageAvailable=false;}
const types={attack:'攻击',skill:'战术',reaction:'应对',equipment:'装备'};
function saved(){try{return G.restore(localStorage.getItem(SAVE_KEY));}catch{return null;}}
function save(){if(!run)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(run));storageAvailable=true;}catch{storageAvailable=false;toast('浏览器无法保存进度，请保持页面开启。');}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function btn(label,action,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function art(key,cls=''){return A.icon(key,cls);}
function header(){return `<header class="topbar"><button class="wordmark" data-action="home" aria-label="任务主菜单">${art('eagle')}<span>黑暗远征<small>DARK EXPEDITION</small></span></button><div class="top-center"><span class="tiny-dot"></span> 帝国边境星区 <b>/</b> M41.998</div><nav>${btn('行动记录','history','nav-button')}${btn('规则档案','help','nav-button')}${btn(fast?'极速 ◇':'动画 ◇','speed','nav-button',`aria-label="${fast?'切换标准动画':'切换极速动画'}"`)}${run&&view==='game'?btn('保存并返回','menu','nav-button exit'):''}</nav></header>`;}
function home(){let current=saved();return `${header()}<main class="landing"><section class="intro"><div class="eyebrow"><span></span> 无光之域 · 灰烬巢都</div><div class="edition">WARHAMMER 40,000 <span>FAN GAME</span></div><h1>黑暗<span>远征</span></h1><p class="intro-line">在四十一千年的黑暗中，<br>让最后一道命令抵达。</p><div class="intro-rule"></div><p class="intro-copy">巢都失联。信号被亚空间风暴吞噬。<br>选择你的先锋，整备武装，深入灰烬圣堂。<br>每一张卡牌，都是生还的可能。</p><div class="mission-stats"><div><strong>03</strong><span>可选职业</span></div><div><strong>13</strong><span>远征遭遇</span></div><div><strong>01</strong><span>最终目标</span></div></div><div class="intro-foot">单人卡牌冒险 <i>·</i> 本地自动存档 <i>·</i> 无需联网</div></section><section class="deployment"><div class="section-title"><span>01 / 选择远征先锋</span><span>SELECT OPERATIVE</span></div><div class="class-grid">${Object.entries(D.classes).map(([id,c],i)=>`<button class="class-card ${chosenClass===id?'selected':''}" data-action="class" data-id="${id}" aria-pressed="${chosenClass===id}"><div class="class-top"><span>0${i+1}</span><span>${chosenClass===id?'已选择 ◈':'◇'}</span></div><div class="class-art">${A.portrait(c.art)}</div><div class="class-caption"><small>${c.latin}</small><h2>${c.name}</h2><p>${c.subtitle}</p><div class="tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></button>`).join('')}</div><div class="deploy-brief"><div><span class="label">战术简报 / ${D.classes[chosenClass].name}</span><p>${D.classes[chosenClass].description}</p></div><span class="hp-badge">${D.classes[chosenClass].hp}<small>初始生命</small></span></div><div class="deploy-buttons">${btn('开始远征 <span>→</span>','deploy','primary deploy')}${current?btn('继续远征 <small>'+D.classes[current.classId].name+' · Lv.'+current.level+'</small>','continue','secondary continue'):''}</div><div class="deploy-note"><span class="tiny-dot"></span> ${current?'已检测到本地远征档案':'舰载系统在线 · 等待出发指令'}<span>约 15–25 分钟 / 局</span></div></section></main><footer class="site-footer"><span>玩法灵感：MAOU《卡牌冒险者》系列</span><span>非官方同人作品 · 原创矢量美术 · v1.0</span><a href="README.md" target="_blank" rel="noopener">任务手册 ↗</a></footer>`;}
function bar(label,current,max,cls=''){return `<div class="stat-line ${cls}"><div><span>${label}</span><strong>${current}<em> / ${max}</em></strong></div><div class="meter"><i style="width:${Math.min(100,Math.max(0,current/max*100))}%"></i></div></div>`;}
function statuses(u){return `<div class="statuses">${u.block?`<span>护盾 ${u.block}</span>`:''}${u.burn?`<span class="danger">焚烧 ${u.burn}</span>`:''}${u.suppress?`<span>压制 ${u.suppress}</span>`:''}${u.prepared?`<span>应对待命</span>`:''}</div>`;}
function enemyPanel(){if(run.phase==='combat'||run.phase==='reward'){let u=run.battle.enemy,e=D.enemies[run.battle.enemyKey];return `<section class="side-section enemy-summary"><div class="section-kicker">敌方信号 <span>LV.${e.level}</span></div><div class="unit-heading"><div class="unit-thumb">${A.portrait(e.art)}</div><div><h3>${e.name}</h3><small>${e.title.split(' · ')[1]}</small></div></div>${bar('生命',u.hp,u.maxHp,'health')}${bar('能源',u.energy,u.baseEnergy,'energy')}${statuses(u)}<div class="pile-buttons">${btn('牌堆 <b>'+u.draw.length+'</b>','hidden','pile')}${btn('坟场 <b>'+u.discard.length+'</b>','enemyDiscard','pile')}</div><div class="enemy-equips">${u.equipment.length?u.equipment.map(id=>`<span title="${esc(D.cards[id].text)}">${D.cards[id].name}</span>`).join(''):'装备区 · 暂无装备'}</div></section>`;}
 let en=G.encounter(run),def=en?(D.enemies[en.key]||D.events[en.key]):null;return `<section class="side-section encounter-summary"><div class="section-kicker">${en?'目标档案':'任务档案'}<span>01</span></div><div class="side-emblem">${art(en?def.art:'eagle')}</div><h3>${def?def.name:'重返灰烬巢都'}</h3><p>${def?def.description:'进入失联巢都，回收传讯核心。清除沿途威胁，终止圣堂深处的裂隙仪式。'}</p>${en?.kind==='enemy'?`<div class="mini-metrics"><span>生命 <b>${def.hp}</b></span><span>能源 <b>${def.energy}</b></span><span>等级 <b>${def.level}</b></span></div>`:''}</section>`;}
function detailContent(){let c=inspected&&D.cards[inspected.id];return c?`<div class="section-kicker">${types[c.type]} / ${c.attr}<span>${c.cost} 能源</span></div><h3>${c.name}</h3><p>${c.text}</p>${inspected.index!==undefined&&run.phase==='combat'?btn('弃置这张手牌','discard','text-button',`data-index="${inspected.index}"`):'<small>卡牌效果以当前规则档案为准</small>'}`:`<div class="section-kicker">战术终端 <span>◈</span></div><h3>${run.phase==='combat'?'保留手牌，规划下一步':'侦察先于进攻'}</h3><p>${run.phase==='combat'?'悬停或聚焦卡牌查看效果，点击出牌。右键可弃牌；应对牌会在受击时自动触发。':'选择一张遭遇卡查看行动。未选择的遭遇会留在桌面，直到你决定处理它们。'}</p>`;}
function playerPanel(){let c=D.classes[run.classId],u=run.phase==='combat'?run.battle.player:null;return `<section class="side-section player-summary"><div class="unit-heading"><div class="unit-thumb player">${A.portrait(c.art)}</div><div><small>远征先锋 <span class="level">LV.${run.level}</span></small><h3>${c.name}</h3></div></div>${bar('生命',u?u.hp:run.hp,run.maxHp,'health')}${bar(c.resource,u?u.energy:run.baseEnergy,run.baseEnergy,'energy')}${u?statuses(u):''}<div class="xp-row"><span>战功 ${run.xp} / ${run.nextLevel}</span><span class="credit">⟐ ${run.credits} <small>军需</small></span></div><div class="xp-meter"><i style="width:${run.xp/run.nextLevel*100}%"></i></div><div class="pile-buttons">${btn((u?'牌堆':'牌组')+' <b>'+(u?u.draw.length:run.deck.length)+'</b>','deck','pile')}${btn(u?'坟场 <b>'+u.discard.length+'</b>':'牌组检视 ↗',u?'discardPile':'deck','pile')}</div></section>`;}
function progress(){return `<div class="mission-top"><div><span class="eyebrow">EXPEDITION / 01</span><h2>灰烬巢都 <span>${run.bossSpawned?'· 圣堂核心':'· 封锁区'}</span></h2></div><div class="progress-block"><div><span>任务推进</span><b>${String(run.resolved).padStart(2,'0')} <em>/ 13</em></b></div><div class="progress-ticks">${Array.from({length:13},(_,i)=>`<i class="${i<run.resolved?'done':''}"></i>`).join('')}</div></div></div>`;}
function encounterCard(en,index){let enemy=en.kind==='enemy',d=enemy?D.enemies[en.key]:D.events[en.key];return `<button class="encounter-card ${enemy?'hostile':'facility'} ${run.selected===en.uid?'selected':''} ${en.key==='boss'?'boss':''}" data-action="encounter" data-id="${en.uid}"><div class="encounter-head"><span>${enemy?'⚔ 敌对信号':'◇ 可交互设施'}</span><b>${enemy?'LV.'+d.level:'EVENT'}</b></div><div class="encounter-art">${enemy?A.portrait(d.art):art(d.art)}<div class="art-index">${String(index+1).padStart(2,'0')}</div></div><div class="encounter-caption"><small>${enemy?d.title.split(' · ')[1]:d.subtitle}</small><h3>${d.name}</h3><div class="encounter-bottom"><span>${enemy?'生命 '+d.hp+' · 军需 +'+d.credits:'探索此处'}</span><span>↗</span></div></div></button>`;}
function eventPanel(){let en=G.encounter(run);if(!en)return `<div class="action-panel idle"><div class="signal-icon">⌖</div><div><h3>选择下一次遭遇</h3><p>未处理的信号仍将保留。留意伤势，为最后的交战储备资源。</p></div><span class="small-label">等待指令</span></div>`;if(en.kind==='enemy'){let e=D.enemies[en.key];return `<div class="action-panel"><div><div class="label">交战许可 / LV.${e.level}</div><h3>${e.name}</h3><p>胜利获得 ${e.xp} 战功、${e.credits} 军需。战后伤势持续。</p></div>${btn(en.key==='boss'?'终止裂隙仪式 →':'进入战斗 →','battle','primary')}</div>`;}
 let e=D.events[en.key],choices='';if(en.key==='armory'){choices=D.classes[run.classId].rewards.map(id=>`<button class="event-choice card-choice" data-action="event" data-choice="take" data-value="${id}">${art(D.cards[id].art)}<span><b>${D.cards[id].name}</b><small>${D.cards[id].text}</small></span></button>`).join('');}
 else if(en.key==='purge')choices=btn('选择要移除的牌 · 5 军需','purge','secondary');
 else if(en.key==='merchant')choices=['med','regroup','deflect','sight'].map((id,i)=>`<button class="event-choice" data-action="event" data-choice="buy" data-value="${id}" title="${D.cards[id].text}"><b>${D.cards[id].name}</b><small>${[6,7,7,9][i]} 军需 · ${D.cards[id].cost} 费</small></button>`).join('');
 else choices=e.choices.filter(c=>c.id!=='leave').map(c=>`<button class="event-choice" data-action="event" data-choice="${c.id}"><b>${c.label}</b><small>${c.detail}</small></button>`).join('');
 return `<div class="event-actions"><div class="event-actions-title"><span>${e.name} <small>/ 选择行动</small></span>${btn('离开此处 →','event','text-button','data-choice="leave"')}</div><div class="event-options">${choices}</div></div>`;}
function backpack(){return `<div class="backpack"><div><span class="label">随身补给</span><small>${run.backpack.length} / ${D.RULES.backpackSlots}</small></div>${run.backpack.length?btn(art('med')+'<span>医疗包<small>恢复 6 生命 · 点击使用</small></span>','item','item-slot'): '<div class="item-slot empty">＋<span>背包为空<small>从补给站获取物资</small></span></div>'}</div>`;}
function exploration(){return `<div class="explore-area"><div class="field-label"><span><i class="tiny-dot"></i> ${run.bossSpawned?'最终目标已锁定':'探测到 '+run.field.length+' 处信号'}</span><span>遭遇牌堆 <b>${run.queue.length}</b></span></div><div class="encounter-row">${run.field.map(encounterCard).join('')}</div>${eventPanel()}</div><div class="explore-bottom">${backpack()}<div class="transmission"><span class="label">最新传讯</span><p>${esc(run.history.at(-1))}</p></div></div>`;}
function handCard(id,index){let c=D.cards[id],reason=G.canPlay(run,'player',index);return `<button class="hand-card ${c.type} ${reason?'unavailable':''}" data-action="play" data-index="${index}" data-card="${id}" aria-label="${c.name}，${c.cost}费，${c.text}${reason?'，'+reason:''}"><div class="hand-card-top"><b class="cost">${c.cost}</b><span>${types[c.type]}</span></div><div class="hand-art">${art(c.art)}</div><h4>${c.name}</h4><p>${c.text}</p><div class="hand-attr">${c.attr}</div></button>`;}
function combat(){let b=run.battle,u=b.player,v=b.enemy;return `<div class="battle-area"><div class="enemy-hand" aria-label="敌方手牌 ${v.hand.length} 张">${v.hand.map((_,i)=>`<div class="card-back" style="--tilt:${(i-(v.hand.length-1)/2)*3}deg">${art('eagle')}</div>`).join('')}<span>敌方手牌 · ${v.hand.length}</span></div><div class="battle-center"><div class="round-seal"><span>ROUND</span><strong>${String(b.round).padStart(2,'0')}</strong><small>${busy?'敌方行动':'你的回合'}</small></div><div class="battle-message">${b.last?`${b.last.side==='player'?D.classes[run.classId].name:v.name} · ${D.cards[b.last.card].name}`:'武装已就绪。等待你的第一条指令。'}</div><div class="battle-feed">${b.log.slice(-3).map(t=>`<p>${esc(t)}</p>`).join('')}</div></div><div class="combat-controls"><div class="equipment-row"><span class="label">装备 ${u.equipment.length} / 2</span>${u.equipment.map((id,i)=>btn(art(D.cards[id].art)+'<span>'+D.cards[id].name+'<small>点击卸下至坟场</small></span>','unequip','equipped',`data-index="${i}" title="${D.cards[id].text}"`)).join('')}${u.equipment.length===0?'<span class="equipment-empty">打出装备牌，持续至本场战斗结束</span>':''}${u.prepared?`<span class="prepared">◇ ${D.cards[u.prepared].name}待命</span>`:''}</div><div class="turn-control"><span>${u.energy} <small>/ ${u.baseEnergy} 能源</small></span>${btn(busy?'敌方行动中…':'结束回合 →','end','primary',busy?'disabled':'')}<small>保留手牌 · 下回合抽 2 张</small></div></div><div class="hand-zone"><div class="hand-meta"><span>战术手牌 <b>${u.hand.length} / 10</b></span>${btn(discardMode?'取消弃牌':'弃牌模式','discardMode','text-button')}<span>${discardMode?'点击一张手牌将其弃置':'点击出牌 · 右键弃置'}</span></div><div class="hand-row">${u.hand.length?u.hand.map(handCard).join(''):'<div class="empty-hand">手牌已用尽。结束回合，等待新的战术指令。</div>'}</div></div></div><div class="battle-footer">${btn('行动记录 ↗','history','text-button')}${btn('医疗包 '+run.backpack.length+' / 1','item','text-button',!run.backpack.length?'disabled':'')}<span class="small-label">应对自动触发 · 伤害可追溯</span></div>`;}
function reward(){let e=D.enemies[run.battle.enemyKey];return `<div class="reward-screen"><div class="reward-sigil">${art('eagle')}</div><div class="eyebrow">ENGAGEMENT COMPLETE</div><h2>敌对信号已清除</h2><p>${e.name}已被击败。重新整备，继续向圣堂核心推进。</p><div class="reward-values"><div><b>+${run.reward.xp}</b><span>战功</span></div><div><b>+${run.reward.credits}</b><span>军需</span></div><div><b>${run.hp}<em>/${run.maxHp}</em></b><span>当前生命</span></div></div>${btn('继续远征 →','claim','primary')}<small>奖励已记录 · 伤势将持续至后续遭遇</small></div>`;}
function endScreen(){let win=run.phase==='victory';return `<div class="ending ${win?'victory':'defeat'}"><div class="ending-art">${art(win?'eagle':'skull')}</div><div class="eyebrow">${win?'MISSION ACCOMPLISHED':'SIGNAL LOST'}</div><h1>${win?'长夜之中，使命已达。':'信号，归于沉寂。'}</h1><p>${win?'传讯核心重新亮起。裂隙仪式已终止，灰烬巢都的求援信号终于穿过风暴。':'你的最后一次传讯停在灰烬深处。远征失败，但下一名先锋将接过这道命令。'}</p><div class="ending-stats"><div><strong>${run.level}</strong><span>先锋等级</span></div><div><strong>${run.battlesWon}</strong><span>击败敌人</span></div><div><strong>${run.resolved}/13</strong><span>完成遭遇</span></div><div><strong>${run.credits}</strong><span>剩余军需</span></div></div><div class="ending-buttons">${btn('新的远征 →','new','primary')}${btn('查看行动记录','history','secondary')}</div><small>每一场远征，都是一次新的选择。</small></div>`;}
function gameView(){if(['victory','defeat'].includes(run.phase))return `${header()}<main class="end-main">${endScreen()}</main>${footer()}`;return `${header()}<main class="game-layout"><aside class="sidebar">${enemyPanel()}<section class="side-section detail-panel" id="card-detail">${detailContent()}</section>${playerPanel()}</aside><section class="tabletop">${progress()}${run.phase==='combat'?combat():run.phase==='reward'?reward():exploration()}</section></main>${footer()}`;}
function footer(){return `<footer class="game-footer"><span><i class="tiny-dot"></i> ${storageAvailable?'进度已自动保存至本机':'存档不可用 · 请勿关闭页面'}</span><span>灰烬远征 / 非官方同人作品</span><span>${run.phase==='combat'?'战斗进行中':run.phase==='adventure'?'等待行动指令':'任务状态已更新'}</span></footer>`;}
function render(){document.body.classList.toggle('fast',fast);$('#app').innerHTML=view==='home'?home():gameView();}
function openModal(title,content,cls=''){lastFocus=document.activeElement;modal=title;$('#modal-root').innerHTML=`<div class="modal-backdrop" data-action="closeBackdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="${title}"><div class="modal-head"><div><small>舰载终端 / ARCHIVE</small><h2>${title}</h2></div>${btn('×','close','close',`aria-label="关闭${title}"`)}</div><div class="modal-content">${content}</div></section></div>`;$('.modal .close').focus();}
function closeModal(){modal='';$('#modal-root').innerHTML='';if(lastFocus?.isConnected)lastFocus.focus();}
function cardList(ids,mode){if(!ids.length)return '<p class="modal-empty">这里暂时没有卡牌。</p>';return `<div class="archive-cards">${ids.map((id,index)=>{let c=D.cards[id];return `<article class="archive-card">${art(c.art)}<div><small>${c.cost} 费 / ${types[c.type]} / ${c.attr}</small><h3>${c.name}</h3><p>${c.text}</p>${mode==='remove'?btn('移除 · 5 军需','event','secondary small',`data-choice="remove" data-value="${index}"`):''}</div></article>`;}).join('')}</div>`;}
function help(){openModal('规则档案',`<div class="rules-intro"><b>一名先锋，一副牌组，一段远征。</b><p>通过选择遭遇、保留手牌和管理能源，抵达并击败灰烬圣堂的最终敌人。</p></div><div class="help-grid"><section><h3>01 / 探索与成长</h3><p>同时展示三张遭遇。选择后处理战斗或事件，其他遭遇保留。共 12 次普通遭遇，全部处理后出现最终敌人。战后伤势持续，战功用于晋升，军需用于买牌或删牌。</p><p>每次晋升生命上限 +3，恢复 3 点生命。升级所需战功从 2 开始逐级 +1。基础能源为 1 + 等级除以 2 向下取整。</p></section><section><h3>02 / 回合与卡牌</h3><p>双方起手 3 张，手牌上限 10。各自首回合不额外抽牌；之后每回合抽 2 张。回合结束保留手牌；己方回合开始能源重置为基础值。回能牌可临时超过基础值。</p><p>牌堆空时，坟场洗回牌堆；没有可抽牌时不产生疲劳伤害。右键或详情中的弃置按钮可把手牌放入坟场。</p></section><section><h3>03 / 反射与装备</h3><p>偏转力场在手牌中会自动应对直接攻击，也可手动打出待命。一次受击最多触发一张，反射不触发连锁反射。先结算反射，再结算护甲、护盾与剩余伤害。</p><p>装备位为 2，每件占一位，效果可叠加。点击装备可卸下到坟场。战后装备重回完整牌组；背包是独立的一个医疗包位置。</p></section><section><h3>04 / 状态与胜负</h3><p>物理伤害受动力甲减免，其他直接伤害仍会被护盾吸收。护盾在下次己方回合开始清零。焚烧在己方回合开始造成等同层数的生命损失，然后减一层；它忽略护甲、护盾及反射。压制每回合少抽一张，持续指定回合。</p><p>双方使用同一规则。生命归零即失败；一次结算双方同时归零时判定玩家失败。击败最终敌人后远征胜利。</p></section></div><details class="provenance"><summary>参考规则与原型假设（设计记录）</summary><p>已验证的参考结构：三张遭遇、起手三张、手牌保留与十张上限、双方牌堆和坟场、零费攻击、付费法术、临时回能、反弹、装备与背包、经验金币、伤势持续、分岔路和付费删牌。</p><p>原型假设：抽牌与资源重置时点、坟场洗回、自动应对的完整顺序、双装备位及叠加、升级数值、商店与军械获取方式、13 次遭遇与首领通关条件。新卡效果、状态数值和三个职业的牌组为本次设计。未声称精确复刻原作。</p><p>两作前期共有骨架已确认；试玩职业分别为法师与魔女，初始牌组不同。未对完整职业、后期或隐藏机制做同等核实，故不推断未经验证的版本差异。</p></details>`,'wide');}
function inspect(el){let id=el.dataset.card;if(!id)return;inspected={id,index:Number(el.dataset.index)};let panel=$('#card-detail');if(panel)panel.innerHTML=detailContent();}
async function action(e){let el=e.target.closest('[data-action]');if(!el)return;let ac=el.dataset.action;if(busy&&!['history','help','close','speed'].includes(ac))return;
 switch(ac){
 case 'class':chosenClass=el.dataset.id;render();break;
 case 'deploy':if(saved()&&!['victory','defeat'].includes(saved().phase))openModal('开始新的远征',`<p>本机已有一份进行中的远征。开始新远征将替换这份存档。</p><div class="modal-actions">${btn('返回','close','secondary')}${btn('开始新远征','confirmDeploy','primary')}</div>`);else deploy();break;
 case 'confirmDeploy':closeModal();deploy();break;
 case 'continue':run=saved();if(run){view='game';render();}else toast('没有有效的远征存档。');break;
 case 'home':case 'menu':if(run)save();view='home';render();break;
 case 'new':view='home';render();break;
 case 'encounter':G.select(run,el.dataset.id);inspected=null;save();render();break;
 case 'battle':discardMode=false;G.beginBattle(run);inspected=null;save();render();break;
 case 'discardMode':discardMode=!discardMode;render();break;
 case 'play':{if(discardMode){G.discard(run,Number(el.dataset.index));discardMode=false;inspected=null;save();render();toast('卡牌已弃置到坟场。');break;}let result=G.playCard(run,'player',Number(el.dataset.index));if(!result.ok){toast(result.reason);return;}inspected=null;save();render();$('.battle-center')?.classList.add('impact');break;}
 case 'end':discardMode=false;busy=true;render();await new Promise(r=>setTimeout(r,fast?0:450));G.endTurn(run);busy=false;inspected=null;save();render();break;
 case 'discard':G.discard(run,Number(el.dataset.index));inspected=null;save();render();break;
 case 'unequip':G.unequip(run,Number(el.dataset.index));save();render();break;
 case 'item':{let r=G.useItem(run);if(!r.ok)toast(r.reason);else{save();render();toast('医疗包已使用，恢复最多 6 点生命。');}break;}
 case 'event':{let value=el.dataset.choice==='remove'?Number(el.dataset.value):el.dataset.value;let result=G.eventAction(run,el.dataset.choice,value);if(!result.ok){toast(result.reason||'此行动暂不可执行');return;}closeModal();inspected=null;save();render();break;}
 case 'purge':openModal('战术重整 · 选择移除',`<p>花费 5 军需，移除本次远征中的一张牌。至少保留 5 张。当前军需：${run.credits}</p>${cardList(run.deck,'remove')}`,'wide');break;
 case 'claim':G.claimReward(run);inspected=null;save();render();break;
 case 'deck':openModal(run.phase==='combat'?'我方剩余牌堆（不按抽取顺序）':'本次远征牌组',cardList(run.phase==='combat'?[...run.battle.player.draw].sort():run.deck),'wide');break;
 case 'discardPile':openModal('我方坟场',cardList(run.battle.player.discard),'wide');break;
 case 'enemyDiscard':openModal('敌方坟场 · 已公开卡牌',cardList(run.battle.enemy.discard),'wide');break;
 case 'hidden':toast('敌方牌堆内容不可见。你可以查看已公开的坟场。');break;
 case 'help':help();break;
 case 'history':openModal('行动记录',run?`<ol class="history-list">${run.history.map((t,i)=>`<li><span>${String(i+1).padStart(3,'0')}</span>${esc(t)}</li>`).join('')}</ol>`:'<p class="modal-empty">远征尚未开始。等待第一条指令。</p>');$('.modal-content').scrollTop=$('.modal-content').scrollHeight;break;
 case 'speed':fast=!fast;try{localStorage.setItem('dark-expedition.fast',fast?'1':'0');}catch{}render();toast(fast?'极速模式：跳过行动等待与动画。':'标准模式：显示简洁的行动反馈。');break;
 case 'close':closeModal();break;
 case 'closeBackdrop':if(e.target===el)closeModal();break;
 }
}
function deploy(){discardMode=false;run=G.newRun(chosenClass);view='game';inspected=null;save();render();openModal('远征须知',`<div class="tutorial"><p><b>01 · 选择遭遇</b>桌面同时保留三张敌人或设施卡。先查看目标，再决定是否交战。</p><p><b>02 · 组合出牌</b>起手三张，点击使用。零费攻击与付费武器可以组合，能源不足时使用战术整备。</p><p><b>03 · 留牌应对</b>结束回合保留手牌，下回合抽两张。力场应对牌在受击时自动触发。</p><p><b>04 · 保存实力</b>伤势跨战斗保留。补给站回血，军械库获得新牌。处理全部遭遇后击败最终敌人。</p></div><div class="modal-actions">${btn('明白，开始行动 →','close','primary')}</div>`);}
document.addEventListener('click',action);
document.addEventListener('mouseover',e=>{let el=e.target.closest('[data-card]');if(el)inspect(el);});
document.addEventListener('focusin',e=>{let el=e.target.closest('[data-card]');if(el)inspect(el);});
document.addEventListener('contextmenu',e=>{let el=e.target.closest('[data-action="play"]');if(!el||busy||modal)return;e.preventDefault();G.discard(run,Number(el.dataset.index));inspected=null;save();render();toast('卡牌已弃置到坟场。');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal){closeModal();return;}if(e.key==='Tab'&&modal){const items=Array.from(document.querySelectorAll('.modal button,.modal a,.modal summary')).filter(x=>!x.disabled);let first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
render();
